name: Blob Uploader

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      AZURE_STORAGE_ACC_NAME:
        required: true
        type: string
      AZURE_CONTAINER_NAME:
        required: true
        type: string 
      APP_NAME:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string

jobs:
  pack-code-to-blob:
    runs-on: runner-utility

    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ${{ inputs.workspace }}

      - name: Extract workspace
        run: |
          tar -xzf ${{ inputs.workspace }}/workspace.tar.gz --strip-components 1
        continue-on-error: true

      - name: az cli
        run: |
          az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
      
      - name: blob-uploader
        run: |
          ls -lrt
          ls -la ./build/

          #### Prepare file to upload ####
          zip -r ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.zip ./build/

          #### Start Upload ####
          echo "Uploading Application To Azure Blob : ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}"
          az storage blob upload --account-name ${{inputs.AZURE_STORAGE_ACC_NAME}} \
          --container-name ${{inputs.AZURE_CONTAINER_NAME}} \
          -n mpay/modernization/batch/${{ inputs.APP_VERSION }}/${{ inputs.APP_NAME }}/${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.zip \
          --file ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.zip

