name: helm-deploy

on:
  workflow_call:
    inputs:
        JobEnvironment:
          required: true
          type: string
        SourceCodeBranch:
          required: true
          type: string
        HELM_VALUES_REPO:
            required: true
            type: string
        HELM_VALUES_BRANCH:
            required: true
            type: string 
        AKS_RESOURCE_GROUP:
            required: true
            type: string
        AKS_NAME:
            required: true
            type: string
        APP_NAME:
          required: true
          type: string
        APP_VERSION:
          required: true
          type: string
        AZURE_STORAGE_ACC_NAME:
          required: true
          type: string
        workspace:
          required: true
          type: string

jobs:
  helm-deploy:
    runs-on: runner-utility
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      #   with:
      #       repository: ${{inputs.HELM_VALUES_REPO}} #helm values repo #helm values repo (MuZikZz-Org/Helm-Vaules)
      #       ref: ${{inputs.HELM_VALUES_BRANCH}} #main
      #       # token: ${{ secrets.PAT }}
      # - run: |
      #     ls -R
      #     echo "Check env"
      #     helm version
      - name: Download workspace artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ${{ inputs.workspace }}

      - name: Extract workspace
        run: |
          tar -xzf ${{ inputs.workspace }}/workspace.tar.gz --strip-components 1
        continue-on-error: true

      - name: az cli
        run: |
          az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
          
      - name: Deploy TO AKS Cluster
        working-directory: ./helmvalue
        run: |
            echo "Set context k8s"
            az aks get-credentials --resource-group ${{inputs.AKS_RESOURCE_GROUP}} --name ${{inputs.AKS_NAME}}

            if [[ ${{inputs.JobEnvironment}} == "feature-branch" ]]; then
              echo "Original Branch Name: ${{inputs.SourceCodeBranch}}"
              ## reformat feature branch ##
              finalBranchName=$(echo ${{inputs.SourceCodeBranch}} | sed "s|/|-|g")
              echo "Namespace: ${finalBranchName}"
                ## create namespace ##
              kubectl create namespace ${finalBranchName} || true
            
            else
              finalBranchName=$(echo ${{inputs.JobEnvironment}})
              echo "Namespace: ${finalBranchName}"
            fi

            helm repo add azblob https://${{inputs.AZURE_STORAGE_ACC_NAME}}.blob.core.windows.net/charts/${{inputs.APP_NAME}}
            helm repo update 

            helm upgrade --install ${{inputs.APP_NAME}} azblob/${{inputs.APP_NAME}} \
            --version ${{inputs.APP_VERSION}} \
            --namespace ${finalBranchName} \
            --set image.tag=${{inputs.APP_VERSION}} \
            --values ${{inputs.APP_NAME}}/values-${{inputs.JobEnvironment}}.yaml 

