name: Helm build chart

on:
  workflow_call:
    inputs:
      Project:
        required: true
        type: string
      HELM_TEMPLATE_REPO:
        required: true
        type: string
      HELM_TEMPLATE_BRANCH:
        required: true
        type: string 
      AZURE_STORAGE_ACC_NAME:
        required: true
        type: string
      AZURE_CONTAINER_NAME:
        required: true
        type: string 
      APP_NAME:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string
      workspace:
          required: true
          type: string

jobs:
  helm-chart-builder:
    runs-on: runner-utility

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{inputs.HELM_TEMPLATE_REPO}} #brightza008/poc-helmchart@minikube
      #     ref: ${{inputs.HELM_TEMPLATE_BRANCH}}
      - name: Download workspace artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ${{ inputs.workspace }}

      - name: Extract workspace
        run: |
          tar -xzf ${{ inputs.workspace }}/workspace.tar.gz --strip-components 1
        continue-on-error: true

      - name: az cli
        run: |
          az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
      
      - name: helm build chart
        working-directory: ./helmchart
        run: | 
          #### Preparation Helm Template ####
          mkdir -p azure-helm-repository/${{ inputs.Project }}/${{inputs.APP_NAME}}
          mv buildchart ./${{inputs.APP_NAME}}

          #### Add helm metadata####
          yq -i '.image.tag="${{inputs.APP_VERSION}}"'    ./${{inputs.APP_NAME}}/values.yaml
          yq -i '.applicationName="${{inputs.APP_NAME}}"' ./${{inputs.APP_NAME}}/values.yaml
          yq ./${{inputs.APP_NAME}}/values.yaml -o json
          yq -i '.name="${{inputs.APP_NAME}}"'            ./${{inputs.APP_NAME}}/Chart.yaml
          yq -i '.version="${{inputs.APP_VERSION}}"'      ./${{inputs.APP_NAME}}/Chart.yaml
          yq -i '.appVersion="${{inputs.APP_VERSION}}"'   ./${{inputs.APP_NAME}}/Chart.yaml
          yq ./${{inputs.APP_NAME}}/Chart.yaml -o json

          helm dependency update ${{inputs.APP_NAME}}
          helm package \
            --app-version ${{inputs.APP_VERSION}} \
            --version ${{inputs.APP_VERSION}} \
            ./${{inputs.APP_NAME}}

          cp ./${{inputs.APP_NAME}}-${{inputs.APP_VERSION}}.tgz ./azure-helm-repository/${{ inputs.Project }}/${{inputs.APP_NAME}}/
          helm repo index ./azure-helm-repository/${{ inputs.Project }}/${{inputs.APP_NAME}} ## add index catalog into App_name dir

          #### Start Upload ####
          az storage blob upload-batch --overwrite --account-name ${{inputs.AZURE_STORAGE_ACC_NAME}} \
          --destination ${{inputs.AZURE_CONTAINER_NAME}} \
          --source ./azure-helm-repository

