name: Maven Build 
on: 
  workflow_call:
jobs:
  mvn-build:
    runs-on: java21
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: maven-build
        run: |
            mvn -U clean package
            ls -lrt
