name: Maven Build 
on: 
  workflow_call:
    inputs:
        workspace:
          required: true
          type: string
jobs:
  mvn-build:
    runs-on: java21
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: maven-build
        run: |
            mvn -U clean package
            ls -lrt

      - name: Save workspace
        run: |
         tar -czf workspace.tar.gz ./*
        continue-on-error: true

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v2
        with:
            name: workspace
            path: workspace.tar.gz