name: Maven Build 
on: 
  workflow_call:
    inputs:
        workspace:
          required: true
          type: string

jobs:
  mvn-build:
    runs-on: java21
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ${{ inputs.workspace }}

      - name: Extract workspace
        run: |
          tar -xzf ${{ inputs.workspace }}/workspace.tar.gz --strip-components 1
        continue-on-error: true

      - name: maven-build
        working-directory: ./app
        run: |
            mvn -U clean package
            ls -lrt

      - name: Save workspace
        run: |
         touch ../workspace.tar.gz
         tar --exclude=workspace.tar.gz -czf workspace.tar.gz ../.
        continue-on-error: true

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v2
        with:
            name: workspace
            path: workspace.tar.gz