name: Nodejs Build 
on: 
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
jobs:
  npm-build:
    runs-on: nodejs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: npm-build
        run: |
            npm install
            ls -lrt

      - name: Save workspace
        run: |
         tar -czf workspace.tar.gz .
        continue-on-error: true

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v2
        with:
            name: workspace
            path: workspace.tar.gz