name: Nodejs Build 
on: 
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
jobs:
  npm-build:
    runs-on: nodejs
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ${{ inputs.workspace }}

      - name: Extract workspace
        run: |
          tar -xzf ${{ inputs.workspace }}/workspace.tar.gz --strip-components 1
        continue-on-error: true

      - name: npm-build
        run: |
            npm install
            npm run build
            ls -lrt

      - name: Save workspace
        run: |
         touch workspace.tar.gz
         tar --exclude=workspace.tar.gz -czf workspace.tar.gz .
        continue-on-error: true

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v2
        with:
            name: workspace
            path: workspace.tar.gz