name: POC_package_versioning
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      Runtime:
        required: true
        type: string
      JobEnvironment:
        required: true
        type: string
    outputs:
      PACKAGE_VERSION:
        description: "set output"
        value: ${{ jobs.java-maven.outputs.packageversion_output }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Runtime Input
        run: echo "Runtime is ${{ github.event.inputs.Runtime }}"

  nodejs:
    if: ${{ inputs.Runtime == 'node' }}
    outputs:
      packageversion_output: ${{ steps.json_properties.outputs.PackageVersion }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy -y

      - name: Get current date
        id: date
        run: |
            echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Example Dev/Sit env.
        id: json_properties
        run: |
          groovy -e '''
            import hudson.model.*
              def json = new File("package.json").text
              def parsedJson = new groovy.json.JsonSlurper().parseText(json)
              def packageVersionInJson =  parsedJson.version
              println "Package Version (package.json): ${packageVersionInJson}"

                // For DEV ENV //
                def versionSplit = packageVersionInJson.split("\\.")
                int lastDigitVersion = "${versionSplit[versionSplit.size() - 1]}".toInteger()
                String perfixVersion = "${versionSplit[0]}.${versionSplit[1]}"
                int nextVersion = lastDigitVersion + 1
                String newVersion = "${perfixVersion}.${nextVersion}"
                PackageVersion = "${newVersion}".trim()
                println "DEV Version: ${PackageVersion}"
                
                
                // For SIT ENV //
                println "${{steps.date.outputs.today}}"
                PackageVersion = "${packageVersionInJson}-${{steps.date.outputs.today}}-${{github.run_number}}".trim()
                println "SIT Version: ${PackageVersion}"

                def env = System.getenv("${PackageVersion}")
                //def version = env["${PackageVersion}"]
                println "${env}"
          '''
          echo "Print out of groovy: ${version}" 

          # echo "PackageVersion=${PackageVersion}" >> $GITHUB_OUTPUT

  java-maven:
    if: ${{ inputs.Runtime == 'java' }}
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.set-package-version.outputs.PACKAGE_VERSION }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy -y

      - name: Get current date
        id: date
        run: |
            echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
            echo "JOB_ENVIRONMENT=${{ inputs.JobEnvironment }}" >> $GITHUB_ENV
      - name: Example Dev/Sit env.
        id: set-package-version
        run: |
          groovy -e '''
            import hudson.model.*
            // Assign input to a variable
            def jobEnvironment = System.getenv("JOB_ENVIRONMENT")
            println "Job Environment: ${jobEnvironment}"

              def pomFile = new File("pom.xml").text
              def xml = new XmlSlurper().parseText(pomFile)
              def packageVersionInXml = xml.version.text()
              println "Package Version (pom.xml): ${packageVersionInXml}"

              // Initialize PackageVersion variable
              def PackageVersion = ""
              
                // For DEV ENV //
                if ("${jobEnvironment}" == "feature-branch") {
                  def versionSplit = packageVersionInXml.split("\\.")
                  int lastDigitVersion = "${versionSplit[versionSplit.size() - 1]}".toInteger()
                  String perfixVersion = "${versionSplit[0]}.${versionSplit[1]}"
                  int nextVersion = lastDigitVersion + 1
                  String newVersion = "${perfixVersion}.${nextVersion}"
                  PackageVersion = "${newVersion}".trim()
                  println "DEV Version: ${PackageVersion}"
                              
                } else {
                  // For SIT ENV //
                  println "date: ${{steps.date.outputs.today}}"
                  def versionSplit = packageVersionInXml.split("\\.")
                  int lastDigitVersion = "${versionSplit[versionSplit.size() - 1]}".toInteger()
                  String perfixVersion = "${versionSplit[0]}.${versionSplit[1]}"
                  int nextVersion = lastDigitVersion + 1
                  String newVersion = "${perfixVersion}.${nextVersion}"
                  PackageVersion = "${newVersion}-${{steps.date.outputs.today}}-${{github.run_number}}".trim()
                  println "SIT Version: ${PackageVersion}"
                }
                println "Before set output ${PackageVersion}"
                // Set PACKAGE_VERSION output

                // Set PACKAGE_VERSION output
                println "PACKAGE_VERSION=${PackageVersion}"
    
                // Output the PackageVersion value
                println "PackageVersion=${PackageVersion}"
          '''

      - name: Use PACKAGE_VERSION output
        run: |
          echo "Package Version: ${{ steps.set-package-version.outputs.PACKAGE_VERSION }}"

      - name: Print PackageVersion
        run: |
          echo "Package Version: ${{ steps.set-package-version.outputs.PackageVersion }}"
